"""Criação das tabelas iniciais

Revision ID: bbe34d8da50e
Revises: 
Create Date: 2025-06-29 22:53:09.097410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe34d8da50e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('farm_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('total_area', sa.Float(), nullable=True),
    sa.Column('agricultural_area', sa.Float(), nullable=True),
    sa.Column('vegetation_area', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producers_cpf_cnpj'), 'producers', ['cpf_cnpj'], unique=True)
    op.create_index(op.f('ix_producers_id'), 'producers', ['id'], unique=False)
    op.create_index(op.f('ix_producers_name'), 'producers', ['name'], unique=False)
    op.create_table('cultures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producer_id', sa.Integer(), nullable=True),
    sa.Column('crop_year', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cultures_id'), 'cultures', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cultures_id'), table_name='cultures')
    op.drop_table('cultures')
    op.drop_index(op.f('ix_producers_name'), table_name='producers')
    op.drop_index(op.f('ix_producers_id'), table_name='producers')
    op.drop_index(op.f('ix_producers_cpf_cnpj'), table_name='producers')
    op.drop_table('producers')
    # ### end Alembic commands ###
