"""Update dashboard data fields

Revision ID: d7578bc0dbbb
Revises: bbe34d8da50e
Create Date: 2025-06-29 23:48:20.004382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7578bc0dbbb'
down_revision: Union[str, Sequence[str], None] = 'bbe34d8da50e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
